In [2]:
import pandas as pd
import numpy as np

marketing = pd.read_csv('marketing.csv')
marketing['converted'] = marketing.converted.astype("bool")

In [3]:
print(marketing.sample())

         user_id date_served marketing_channel          variant  converted  \
9676  a100006949     1/31/18         Instagram  personalization      False

     language_displayed language_preferred    age_group date_subscribed  \
9676            English            English  30-36 years             NaN

     date_canceled subscribing_channel is_retained
9676           NaN                 NaN         NaN

In [4]:
print(marketing.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10037 entries, 0 to 10036
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              10037 non-null  object
 1   date_served          10021 non-null  object
 2   marketing_channel    10022 non-null  object
 3   variant              10037 non-null  object
 4   converted            10037 non-null  bool
 5   language_displayed   10037 non-null  object
 6   language_preferred   10037 non-null  object
 7   age_group            10037 non-null  object
 8   date_subscribed      1856 non-null   object
 9   date_canceled        577 non-null    object
 10  subscribing_channel  1856 non-null   object
 11  is_retained          1856 non-null   object
dtypes: bool(1), object(11)
memory usage: 872.5+ KB
None

In [5]:
print(marketing.describe(include="all"))

           user_id date_served marketing_channel  variant converted  \
count        10037       10021             10022    10037     10037
unique        7309          31                 5        2         2
top     a100000882     1/15/18         House Ads  control     False
freq            12         789              4733     5091      8946

       language_displayed language_preferred    age_group date_subscribed  \
count               10037              10037        10037            1856
unique                  4                  4            7              31
top               English            English  19-24 years         1/16/18
freq                 9793               9275         1682             163

       date_canceled subscribing_channel is_retained
count            577                1856        1856
unique           115                   5           2
top           4/2/18           Instagram        True
freq              15                 600        1279

In [12]:
channel_dict = {"House Ads": 1, 'Instagram': 2, 
                'Facebook': 3, 'Email': 4, 'Push': 5}
marketing['channel_code'] = marketing['marketing_channel'].map(channel_dict)

print(marketing['channel_code'].head(25))
marketing.head(25)
marketing['marketing_channel'].value_counts()

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    5.0
Name: channel_code, dtype: float64

marketing_channel
House Ads    4733
Instagram    1871
Facebook     1860
Push          993
Email         565
Name: count, dtype: int64

In [7]:
marketing['is_house_ads'] = np.where(
    marketing['marketing_channel'] ==  'House Ads', True, False)

print(marketing.is_house_ads.head(10))
marketing

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: is_house_ads, dtype: bool

,user_id,date_served,marketing_channel,variant,converted,language_displayed,language_preferred,age_group,date_subscribed,date_canceled,subscribing_channel,is_retained,channel_code,is_house_ads
0,a100000029,1/1/18,House Ads,personalization,True,English,English,0-18 years,1/1/18,NaN,House Ads,True,1.0,True
1,a100000030,1/1/18,House Ads,personalization,True,English,English,19-24 years,1/1/18,NaN,House Ads,True,1.0,True
2,a100000031,1/1/18,House Ads,personalization,True,English,English,24-30 years,1/1/18,NaN,House Ads,True,1.0,True
3,a100000032,1/1/18,House Ads,personalization,True,English,English,30-36 years,1/1/18,NaN,House Ads,True,1.0,True
4,a100000033,1/1/18,House Ads,personalization,True,English,English,36-45 years,1/1/18,NaN,House Ads,True,1.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10032,a100007290,1/17/18,Email,control,True,German,German,45-55 years,1/17/18,1/24/18,Email,False,4.0,False
10033,a100007291,1/17/18,Email,control,True,German,German,55+ years,1/17/18,NaN,Email,True,4.0,False
10034,a100007292,1/5/18,Instagram,control,False,German,German,55+ years,1/17/18,NaN,Email,True,2.0,False
10035,a100007293,1/17/18,Email,control,True,German,German,0-18 years,1/17/18,NaN,Email,True,4.0,False
10036,a100007294,1/6/18,Facebook,control,False,German,German,0-18 years,1/17/18,NaN,Email,True,3.0,False

In [8]:
print(marketing['is_retained'].dtype)

object

In [9]:
marketing['is_retained'] = marketing['is_retained'].astype('bool')

In [10]:
print(marketing['is_retained'].dtype)

bool